version: "3.9"

services:
  auth:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env.${ENVIROMENT}
    depends_on:
      - db
    command: bash -c "npm run ${ENVIROMENT}"

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - ./.env.${ENVIROMENT}
    volumes:
      - dbdata:/var/lib/postgresql/data/
    
volumes:
  dbdata:

